### PR TITLE
Add size/number of files for all the published and upcoming HPA runs

### PR DESCRIPTION
**Pull request by sbesson**
These numbers were computed by running the following command

```
for i in 20180831-ftp 20181112-ftp 20181129-ftp 20190109-ftp 20190121-ftp 20190610-ftp  20191007-ftp 20200609-ftp; do echo $i && find /uod/idr/filesets/idr0043-uhlen-humanproteinatlas/$i -type f | wc -l && du -csb /uod/idr/filesets/idr0043-uhlen-humanproteinatlas/$i; done
```

To simplify the calculation of the raw data size/files in the future, this file can be updated for each new published batch.

/cc @dominikl @manics

### CODE REVIEW

**Comment by sbesson** [comment]
Note that the sum of the 7 first published runs is `92622284676108 B /  3433139 files` and seems one run below the numbers currently used in https://github.com/IDR/idr.openmicroscopy.org/blob/2020.08.19/_data/studies.tsv#L52.

I suspect this comes from the fact previous calculation unwillingly included the unpublished run 0 also available on the FTP. Given the 8th run is scheduled for release, I'd propose we don't correct this immediately but correct the numbers for IDR 0.8.6 so that the raw data metrics do not look like they shrinked between releases.

**Comment by joshmoore** [comment]
Is having run0 in its current location a concern?

**Comment by sbesson** [comment]
I would say only for this particular calculation at the moment. The data itself is valid (and accessible via Aspera) although is includes mostly images which exceed the OMERO pyramidal threshold.

If it was confirmed the data _will_ be re-uploaded after being cropped to 3Kx3K, as was discussed with the submitters, I would be in favor of deleting the run0 from disk (and maybe the preliminary uploaded folders too) to reduce the confusion though.

**Comment by dominikl** [comment]
The `run0` data is all in `20180624-ftp` directory, so if we don't include that in Seb's command it should be fine.
Same holds for the other, older directories`20180518-ftp` and `20180320` which were only test data, afaik.

**Pull request merged**
