### PR TITLE
Import configuration changes used for hpa_run_02

### PR DESCRIPTION
**Pull request by sbesson**
These changes were used together with the latest build of IDR-OMERO based on OMERO 5.4.8

### CODE REVIEW

**Comment by sbesson** [comment]
I initially tried putting the `readers.txt` in the root directory and this did not work. So I suspect the path has to be relative to the configuration file passed to `bin/omero import --bulk` - in that case `idr0043-experimentA-bulk.yml`.

I assume the alternative to minimize duplicate would be something along the lines of `reader: "../readers.txt"` and have `experimentA/readers.txt`.

**Comment by joshmoore** [comment]
:+1: for using the `../` but if there's discrepancy between the different fields (include, readers, path) in how they are handling relative paths then it should probably count as a bug against `import.py`.

**Comment by dominikl** [comment]
`../readers.txt` would be nice, if that works. I wouldn't expect that to be different for the different hpa batches.

**Comment by sbesson** [comment]
@dominikl @joshmoore d86c7d7  works around the issue discussed https://github.com/IDR/idr0043-uhlen-humanproteinatlas/pull/9#issuecomment-423908069 question by moving the `readers` key to each dataset bulk file so that the shared bulk file as well as the shared readers file are both relative to it.

The last commit can be tested in dry-run mode i.e. `/opt/omero/server/OMERO.server/bin/omero import -f --bulk experimentA/hpa_run_02/idr0043-experimentA-bulk.yml` should return list of candidates. Additionally removing `experimentA/readers.txt` should result in errors in the file detection.

**Comment by joshmoore** [comment]
Agreed. :+1:

**Pull request merged**
